### ISSUE TITLE
Wanderlust icons are missing

### ISSUE THREAD

**Issue by dmj** [egh/melpa#2]
The icons are not copied to the install directory. Looks like this can be easily fixed in the recipes. But how to properly set 'wl-icon-directory'?

**Comment by egh** [comment]
I had to make a change to the default setting of wl-icon-directory egh/wanderlust@68f717151a4e0613dfd358b7c444dd61318f8460, but that seems to have done it.

**Comment by egh** [comment]
Resolved with 62dd3c2b6c53df97d1b74dccc127eaa870a9ce45, new packages pushed.
